# ************************************************************
# This docker compose file is used to run a local development environment for the project.
# This is not meant to be used in production.
# ************************************************************

services:
  db:
    image: postgres
    container_name: dev-postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
